/**
 * PostgreSQL 表结构。所有语句都是幂等的，进程启动时顺序执行一遍即可建库。
 * FSRS 相关字段（state/due/stability/difficulty/...）直接对应 ts-fsrs 的 Card 结构，
 * 单词和语法点各存一份，这样两者都能走同一套间隔重复调度。
 *
 * 两个约定：
 * - 时间列统一 `timestamp(0)`（不带时区，存 UTC 墙上时间）。连接建立时会 `SET TIME ZONE 'UTC'`，
 *   所以 SQL 里直接写 `now()` 就是 UTC，和 ts-fsrs 生成的 'YYYY-MM-DD HH:MM:SS' 可以直接比大小。
 * - 结构化字段统一 `jsonb`，读出来就是 JS 对象，写进去传 JSON 字符串。
 */

export const DDL: string[] = [];

DDL.push(`CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '学习者',
  level TEXT NOT NULL DEFAULT 'A1',
  goal TEXT NOT NULL DEFAULT 'daily_talk',
  interests JSONB NOT NULL DEFAULT '[]'::jsonb,
  daily_minutes INTEGER NOT NULL DEFAULT 30,
  new_words_per_day INTEGER NOT NULL DEFAULT 8,
  voice TEXT,
  onboarded INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS words (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term TEXT NOT NULL UNIQUE,
  phonetic TEXT,
  pos TEXT,
  meaning_zh TEXT NOT NULL,
  meaning_en TEXT,
  cefr TEXT NOT NULL DEFAULT 'A1',
  theme TEXT,
  example_en TEXT,
  example_zh TEXT,
  source TEXT NOT NULL DEFAULT 'seed',
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_theme ON words(theme)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_cefr ON words(cefr)`);
// findWordByTerm 走大小写不敏感匹配，这里给它一个可用的索引
DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_term_lower ON words(lower(term))`);

// user_words：每个词的掌握状态。produced_count 记录"你主动说/写出来过几次"，
// 这是本站和普通背单词 app 的关键差别：只认得不算掌握。
DDL.push(`CREATE TABLE IF NOT EXISTS user_words (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  word_id INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
  state INTEGER NOT NULL DEFAULT 0,
  due TIMESTAMP(0) NOT NULL DEFAULT now(),
  stability DOUBLE PRECISION NOT NULL DEFAULT 0,
  difficulty DOUBLE PRECISION NOT NULL DEFAULT 0,
  elapsed_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  scheduled_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  learning_steps INTEGER NOT NULL DEFAULT 0,
  reps INTEGER NOT NULL DEFAULT 0,
  lapses INTEGER NOT NULL DEFAULT 0,
  last_review TIMESTAMP(0),
  produced_count INTEGER NOT NULL DEFAULT 0,
  seen_contexts JSONB NOT NULL DEFAULT '[]'::jsonb,
  starred INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(user_id, word_id)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_uw_due ON user_words(user_id, due)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_uw_state ON user_words(user_id, state)`);

DDL.push(`CREATE TABLE IF NOT EXISTS grammar_points (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title_zh TEXT NOT NULL,
  title_en TEXT NOT NULL,
  cefr TEXT NOT NULL DEFAULT 'A1',
  explain_zh TEXT NOT NULL,
  pattern TEXT,
  examples JSONB NOT NULL DEFAULT '[]'::jsonb,
  pitfalls JSONB NOT NULL DEFAULT '[]'::jsonb,
  ord INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT 'seed'
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS user_grammar (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  grammar_id INTEGER NOT NULL REFERENCES grammar_points(id) ON DELETE CASCADE,
  state INTEGER NOT NULL DEFAULT 0,
  due TIMESTAMP(0) NOT NULL DEFAULT now(),
  stability DOUBLE PRECISION NOT NULL DEFAULT 0,
  difficulty DOUBLE PRECISION NOT NULL DEFAULT 0,
  elapsed_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  scheduled_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  learning_steps INTEGER NOT NULL DEFAULT 0,
  reps INTEGER NOT NULL DEFAULT 0,
  lapses INTEGER NOT NULL DEFAULT 0,
  last_review TIMESTAMP(0),
  error_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(user_id, grammar_id)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_ug_due ON user_grammar(user_id, due)`);

DDL.push(`CREATE TABLE IF NOT EXISTS review_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  kind TEXT NOT NULL,
  item_id INTEGER NOT NULL,
  rating INTEGER NOT NULL,
  mode TEXT NOT NULL DEFAULT 'recall',
  elapsed_ms INTEGER NOT NULL DEFAULT 0,
  reviewed_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_rl_user_time ON review_logs(user_id, reviewed_at)`);

DDL.push(`CREATE TABLE IF NOT EXISTS themes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  zh TEXT NOT NULL,
  en TEXT NOT NULL,
  tags TEXT NOT NULL DEFAULT '',
  last_used_on DATE
)`);

// 一天一条 session。stage_index 记录进行到第几环节，刷新页面能原地续上。
DDL.push(`CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  theme_slug TEXT NOT NULL,
  theme_zh TEXT NOT NULL,
  theme_en TEXT NOT NULL,
  target_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  review_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  grammar_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  stage_index INTEGER NOT NULL DEFAULT 0,
  stages_done JSONB NOT NULL DEFAULT '[]'::jsonb,
  minutes_spent DOUBLE PRECISION NOT NULL DEFAULT 0,
  completed_at TIMESTAMP(0),
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(user_id, day)
)`);

// AI 生成的环节内容缓存：同一天同一环节只生成一次，刷新不重复扣 token。
DDL.push(`CREATE TABLE IF NOT EXISTS stage_content (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  stage TEXT NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(session_id, stage)
)`);

// 错误档案：拼写/语法/发音/用词错误全部落这里，明天的例句和语法点会针对性复现。
DDL.push(`CREATE TABLE IF NOT EXISTS mistakes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  stage TEXT,
  word_id INTEGER,
  grammar_id INTEGER,
  wrong TEXT NOT NULL,
  correct TEXT,
  note_zh TEXT,
  resolved INTEGER NOT NULL DEFAULT 0,
  times INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_mistakes_user ON mistakes(user_id, resolved, created_at)`);

DDL.push(`CREATE TABLE IF NOT EXISTS conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id INTEGER,
  title TEXT NOT NULL DEFAULT '自由对话',
  theme_slug TEXT,
  target_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS chat_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  translation_zh TEXT,
  feedback JSONB,
  used_words JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_msg_conv ON chat_messages(conversation_id, id)`);

DDL.push(`CREATE TABLE IF NOT EXISTS writings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id INTEGER,
  prompt_en TEXT NOT NULL,
  prompt_zh TEXT,
  text TEXT NOT NULL,
  corrected TEXT,
  score INTEGER,
  feedback JSONB,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS speech_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id INTEGER,
  target TEXT NOT NULL,
  transcript TEXT NOT NULL,
  score INTEGER NOT NULL,
  detail JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

// 你自己扔进来的素材（文章/字幕/技术文档），AI 从里面抽词和语法点。
DDL.push(`CREATE TABLE IF NOT EXISTS materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'article',
  raw TEXT NOT NULL,
  summary_zh TEXT,
  word_count INTEGER NOT NULL DEFAULT 0,
  extracted INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS daily_stats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  reviews INTEGER NOT NULL DEFAULT 0,
  correct INTEGER NOT NULL DEFAULT 0,
  new_words INTEGER NOT NULL DEFAULT 0,
  produced INTEGER NOT NULL DEFAULT 0,
  spoken_seconds INTEGER NOT NULL DEFAULT 0,
  minutes DOUBLE PRECISION NOT NULL DEFAULT 0,
  UNIQUE(user_id, day)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_ds_user_day ON daily_stats(user_id, day)`);

/** 建表/播种时用的进程间互斥锁 key，避免多个实例同时初始化。 */
export const SCHEMA_LOCK_KEY = 728417231;

/** 所有表名，reset 脚本用。顺序无关，DROP 时统一带 CASCADE。 */
export const ALL_TABLES = [
  'chat_messages',
  'conversations',
  'daily_stats',
  'grammar_points',
  'materials',
  'mistakes',
  'review_logs',
  'sessions',
  'speech_attempts',
  'stage_content',
  'themes',
  'user_grammar',
  'user_words',
  'users',
  'words',
  'writings',
] as const;
