/**
 * PostgreSQL 表结构。所有语句都是幂等的，进程启动时顺序执行一遍即可建库。
 * FSRS 相关字段（state/due/stability/difficulty/...）直接对应 ts-fsrs 的 Card 结构，
 * 单词和语法点各存一份，这样两者都能走同一套间隔重复调度。
 *
 * 两个约定：
 * - 时间列统一 `timestamp(0)`（不带时区，存 UTC 墙上时间）。连接建立时会 `SET TIME ZONE 'UTC'`，
 *   所以 SQL 里直接写 `now()` 就是 UTC，和 ts-fsrs 生成的 'YYYY-MM-DD HH:MM:SS' 可以直接比大小。
 * - 结构化字段统一 `jsonb`，读出来就是 JS 对象，写进去传 JSON 字符串。
 */

export const DDL: string[] = [];

DDL.push(`CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '学习者',
  level TEXT NOT NULL DEFAULT 'A1',
  goal TEXT NOT NULL DEFAULT 'daily_talk',
  interests JSONB NOT NULL DEFAULT '[]'::jsonb,
  daily_minutes INTEGER NOT NULL DEFAULT 30,
  new_words_per_day INTEGER NOT NULL DEFAULT 10,
  voice TEXT,
  ai_voice TEXT,
  speech_pace TEXT NOT NULL DEFAULT 'normal',
  onboarded INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

// 上面那句是 CREATE TABLE IF NOT EXISTS —— 对已存在的库它什么都不做。
// 新增列必须另写幂等 ALTER，否则老库升级后会在读这些列时直接报错。
//
// voice 和 ai_voice 是两回事，别弄混：
// - voice：浏览器 Web Speech 的语音包名字，给逐句朗读用，离线可用
// - ai_voice：StepFun realtime 的音色 id，给畅聊用，两边名字不通用
/*
 * new_words_per_day 的默认值从 8 提到 10。CREATE TABLE 只对新库生效，
 * 这句把老库里还停在旧默认 8 的档案也顺手抬上来 —— 用户自己调到别的值的不动。
 * 上限 100：设置页滑杆和 API 校验都按这个口径。
 */
DDL.push(`DO $$
BEGIN
  UPDATE users SET new_words_per_day = 10 WHERE new_words_per_day = 8;
END $$`);

DDL.push(`ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_voice TEXT`);
DDL.push(
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS speech_pace TEXT NOT NULL DEFAULT 'normal'`,
);

/*
 * voice_offline 是 2026-08-28 给「自建 Kokoro 预生成」加的一列（'kokoro:xx'）。
 * 2026-09-09 自建 Kokoro 整条下线，服务端朗读只走云端 MiMo（users.voice），
 * 这列不再被读。列本身留着不删 —— 老库升级不该动用户表结构，
 * 测试站旧构建还在写它，同一个 PG 里别互相绊。
 */
DDL.push(`ALTER TABLE users ADD COLUMN IF NOT EXISTS voice_offline TEXT`);

/*
 * 一人一份档案。身份来自上游 ai.xlingo.fun（见 src/lib/auth/config.mjs），
 * 这里只存「上游那个人 ↔ 本地这份档案」的对应关系：
 *
 *   external_id  上游的用户数字 id，存成 TEXT 避免以后上游换成 uuid 要改类型
 *   external_username / external_email  只为了显示和排查，不参与关联
 *
 * external_id 为 NULL 的那条是单人模式留下的历史档案（id=1）。
 * 唯一索引用 partial index：NULL 在 UNIQUE 里本来就互不冲突，但写清楚更保险。
 */
DDL.push(`ALTER TABLE users ADD COLUMN IF NOT EXISTS external_id TEXT`);
DDL.push(`ALTER TABLE users ADD COLUMN IF NOT EXISTS external_username TEXT`);
DDL.push(`ALTER TABLE users ADD COLUMN IF NOT EXISTS external_email TEXT`);
DDL.push(
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_users_external ON users(external_id) WHERE external_id IS NOT NULL`,
);

/*
 * 老库的 users.id 是光秃秃的 INTEGER PRIMARY KEY —— 没有序列，靠代码写死 1。
 * 多人之后必须让它自己发号，否则第二个人注册时 INSERT 不给 id 会直接违反非空约束。
 *
 * 上面的 CREATE TABLE 已经带 GENERATED BY DEFAULT AS IDENTITY，但那句对已存在的
 * 库是空操作，所以老库得单独补。ADD GENERATED 不支持 IF NOT EXISTS，重复执行会
 * 报 55006，用 DO 块吞掉；同时把序列的起点推到当前最大 id 之后，
 * 不然第一次自动发号会撞上历史那条 id=1。
 */
DDL.push(`DO $$
BEGIN
  BEGIN
    ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  EXCEPTION
    WHEN others THEN NULL;  -- 已经是 identity 了
  END;
  PERFORM setval(
    pg_get_serial_sequence('users', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM users), 1)
  );
EXCEPTION
  WHEN others THEN NULL;  -- 没有序列（极老的库且 ADD GENERATED 失败），留给下次
END $$`);

DDL.push(`CREATE TABLE IF NOT EXISTS words (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term TEXT NOT NULL UNIQUE,
  phonetic TEXT,
  pos TEXT,
  meaning_zh TEXT NOT NULL,
  meaning_en TEXT,
  cefr TEXT NOT NULL DEFAULT 'A1',
  theme TEXT,
  example_en TEXT,
  example_zh TEXT,
  source TEXT NOT NULL DEFAULT 'seed',
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

/*
 * 记忆抓手和搭配以前是每次生成 newwords 环节时现问 AI、用完就扔，
 * 同一个词换一批/第二天再出现就再问一遍 —— 慢且烧 token。
 * 存下来之后一个词一辈子只问一次。
 * frq 存 ECDICT 的词频排名，用来在词表里排序和显示"多常用"。
 */
DDL.push(`ALTER TABLE words ADD COLUMN IF NOT EXISTS memory_hook_zh TEXT`);
DDL.push(`ALTER TABLE words ADD COLUMN IF NOT EXISTS collocations JSONB NOT NULL DEFAULT '[]'::jsonb`);
DDL.push(`ALTER TABLE words ADD COLUMN IF NOT EXISTS frq INTEGER NOT NULL DEFAULT 0`);

DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_theme ON words(theme)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_cefr ON words(cefr)`);
// findWordByTerm 走大小写不敏感匹配，这里给它一个可用的索引
DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_term_lower ON words(lower(term))`);

// user_words：每个词的掌握状态。produced_count 记录"你主动说/写出来过几次"，
// 这是本站和普通背单词 app 的关键差别：只认得不算掌握。
DDL.push(`CREATE TABLE IF NOT EXISTS user_words (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  word_id INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
  state INTEGER NOT NULL DEFAULT 0,
  due TIMESTAMP(0) NOT NULL DEFAULT now(),
  stability DOUBLE PRECISION NOT NULL DEFAULT 0,
  difficulty DOUBLE PRECISION NOT NULL DEFAULT 0,
  elapsed_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  scheduled_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  learning_steps INTEGER NOT NULL DEFAULT 0,
  reps INTEGER NOT NULL DEFAULT 0,
  lapses INTEGER NOT NULL DEFAULT 0,
  last_review TIMESTAMP(0),
  produced_count INTEGER NOT NULL DEFAULT 0,
  seen_contexts JSONB NOT NULL DEFAULT '[]'::jsonb,
  starred INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(user_id, word_id)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_uw_due ON user_words(user_id, due)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_uw_state ON user_words(user_id, state)`);

DDL.push(`CREATE TABLE IF NOT EXISTS grammar_points (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title_zh TEXT NOT NULL,
  title_en TEXT NOT NULL,
  cefr TEXT NOT NULL DEFAULT 'A1',
  explain_zh TEXT NOT NULL,
  pattern TEXT,
  examples JSONB NOT NULL DEFAULT '[]'::jsonb,
  pitfalls JSONB NOT NULL DEFAULT '[]'::jsonb,
  ord INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT 'seed'
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS user_grammar (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  grammar_id INTEGER NOT NULL REFERENCES grammar_points(id) ON DELETE CASCADE,
  state INTEGER NOT NULL DEFAULT 0,
  due TIMESTAMP(0) NOT NULL DEFAULT now(),
  stability DOUBLE PRECISION NOT NULL DEFAULT 0,
  difficulty DOUBLE PRECISION NOT NULL DEFAULT 0,
  elapsed_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  scheduled_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  learning_steps INTEGER NOT NULL DEFAULT 0,
  reps INTEGER NOT NULL DEFAULT 0,
  lapses INTEGER NOT NULL DEFAULT 0,
  last_review TIMESTAMP(0),
  error_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(user_id, grammar_id)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_ug_due ON user_grammar(user_id, due)`);

DDL.push(`CREATE TABLE IF NOT EXISTS review_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  kind TEXT NOT NULL,
  item_id INTEGER NOT NULL,
  rating INTEGER NOT NULL,
  mode TEXT NOT NULL DEFAULT 'recall',
  elapsed_ms INTEGER NOT NULL DEFAULT 0,
  reviewed_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_rl_user_time ON review_logs(user_id, reviewed_at)`);

DDL.push(`CREATE TABLE IF NOT EXISTS themes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  zh TEXT NOT NULL,
  en TEXT NOT NULL,
  tags TEXT NOT NULL DEFAULT '',
  last_used_on DATE
)`);

// 一天一条 session。stage_index 记录进行到第几环节，刷新页面能原地续上。
DDL.push(`CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  theme_slug TEXT NOT NULL,
  theme_zh TEXT NOT NULL,
  theme_en TEXT NOT NULL,
  target_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  review_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  grammar_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  stage_index INTEGER NOT NULL DEFAULT 0,
  stages_done JSONB NOT NULL DEFAULT '[]'::jsonb,
  minutes_spent DOUBLE PRECISION NOT NULL DEFAULT 0,
  completed_at TIMESTAMP(0),
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
// 2026-08-28 多主题/天：原来是 UNIQUE(user_id, day)，用户点「进入下一个主题」
// 后当天能再开新 session。约束放宽为「每天最多一条**未完成**」——点下一主题时
// 旧 session 置 completed_at 入历史，不再占坑；还没点就并发开门的极端场景仍被
// 部分唯一索引挡住（不会一天攒一堆半成品）。getOrCreateToday 的 ON CONFLICT
// 随之改成打在这个索引上。
DDL.push(`ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_user_id_day_key`);
DDL.push(`CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_open_per_day
  ON sessions (user_id, day) WHERE completed_at IS NULL`);

// AI 生成的环节内容缓存：同一天同一环节只生成一次，刷新不重复扣 token。
DDL.push(`CREATE TABLE IF NOT EXISTS stage_content (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  stage TEXT NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(session_id, stage)
)`);

// 错误档案：拼写/语法/发音/用词错误全部落这里，明天的例句和语法点会针对性复现。
DDL.push(`CREATE TABLE IF NOT EXISTS mistakes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  stage TEXT,
  word_id INTEGER,
  grammar_id INTEGER,
  wrong TEXT NOT NULL,
  correct TEXT,
  note_zh TEXT,
  resolved INTEGER NOT NULL DEFAULT 0,
  times INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_mistakes_user ON mistakes(user_id, resolved, created_at)`);

DDL.push(`CREATE TABLE IF NOT EXISTS conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id INTEGER,
  title TEXT NOT NULL DEFAULT '自由对话',
  theme_slug TEXT,
  target_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS chat_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  translation_zh TEXT,
  feedback JSONB,
  used_words JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_msg_conv ON chat_messages(conversation_id, id)`);

/*
 * writings 表连同写作环节一起去掉了，这里不再建。
 * 但它仍然留在 ALL_TABLES 里（标了注释），这样在老库上跑一次 db:reset
 * 就能把遗留的表清掉，不会长期挂着一张没人写的表。
 */

DDL.push(`CREATE TABLE IF NOT EXISTS speech_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id INTEGER,
  target TEXT NOT NULL,
  transcript TEXT NOT NULL,
  score INTEGER NOT NULL,
  detail JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

// 你自己扔进来的素材（文章/字幕/技术文档），AI 从里面抽词和语法点。
DDL.push(`CREATE TABLE IF NOT EXISTS materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'article',
  raw TEXT NOT NULL,
  summary_zh TEXT,
  word_count INTEGER NOT NULL DEFAULT 0,
  extracted INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS daily_stats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  reviews INTEGER NOT NULL DEFAULT 0,
  correct INTEGER NOT NULL DEFAULT 0,
  new_words INTEGER NOT NULL DEFAULT 0,
  produced INTEGER NOT NULL DEFAULT 0,
  spoken_seconds INTEGER NOT NULL DEFAULT 0,
  minutes DOUBLE PRECISION NOT NULL DEFAULT 0,
  UNIQUE(user_id, day)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_ds_user_day ON daily_stats(user_id, day)`);

/**
 * dictionary：离线词典（ECDICT）。
 *
 * 为什么和 words 分开而不是合成一张表：
 * - words 是“你在学的词”，百到千量级，带主题、来源、例句，跟 user_words 关联；
 * - dictionary 是“查得到的词”，十万到百万量级，只用于查询。
 * 掘在一起的话，每次拉“今天要学的词”都要在百万行里扭，而且 source 字段
 * 会变成一个既要区分“学习来源”又要区分“是否词典条目”的缝合字段。
 *
 * translation 存 ECDICT 原始的多行中文释义（\n 分隔），definition 存英文释义。
 * frq 是词频排名（越小越常用）0 表示未知；tag 是考纲标签（zk/gk/cet4...）。
 */
DDL.push(`CREATE TABLE IF NOT EXISTS dictionary (
  word TEXT PRIMARY KEY,
  phonetic TEXT,
  definition TEXT,
  translation TEXT,
  pos TEXT,
  collins SMALLINT,
  oxford SMALLINT,
  tag TEXT,
  bnc INTEGER,
  frq INTEGER,
  exchange TEXT,
  detail TEXT,
  audio TEXT
)`);

// 查词走小写匹配（用户选中的词可能带大写或变形）
DDL.push(`CREATE INDEX IF NOT EXISTS idx_dict_word_lower ON dictionary(lower(word))`);
// 按词频挑“值得学的词”时用
DDL.push(`CREATE INDEX IF NOT EXISTS idx_dict_frq ON dictionary(frq) WHERE frq > 0`);

/**
 * word_level：单词的 CEFR 等级（CEFR-J + Octanove，人工标注）。
 *
 * 为什么不复用 dictionary.tag：tag 是考纲收录信息（zk/gk/cet4/cet6/ky/toefl/ielts/gre），
 * 只能当分级的代理，一个词进了 cet4 大纲不等于它就是 B1。实测两者只有 54% 对得上。
 * ECDICT 里也没有 CEFR 列，所以等级只能另存一张表，用 word 关联。
 *
 * 分工是刻意的：这张表只管"这个词是几级"，中文释义、音标、词频仍然全部来自
 * dictionary —— CEFR-J 两份表都不带中文和音标，单独用不了。8493 个词里
 * 8418（99.1%）能 join 上，其中 8115 同时有中文和音标。
 *
 * 表是空的时候选词会自动退回 tag 方案（见 repo/dictionary.ts），
 * 所以先部署后导入不会让新词环节失效。
 *
 * 数据来源和授权见 scripts/import-levels.mjs 顶部。
 */
DDL.push(`CREATE TABLE IF NOT EXISTS word_level (
  word TEXT PRIMARY KEY,
  cefr TEXT NOT NULL,
  -- 词性，CEFR-J 原始标注（noun/verb/adjective…）。同词多词性时取最低那级，这里存对应的词性
  pos TEXT,
  -- 数据来源：cefrj（A1-B2）或 octanove（C1-C2），出问题时能追到是哪份表标的
  src TEXT NOT NULL DEFAULT 'cefrj'
)`);

// 按等级取词是选词的主查询路径
DDL.push(`CREATE INDEX IF NOT EXISTS idx_word_level_cefr ON word_level(cefr)`);

/*
 * app_settings：全站一份的运行时设置，键值对。
 *
 * 现在只存「每个角色挑了清单里的哪个模型」（键 `model.content` 等）。
 * 为什么不放 users 表：这是部署级的选择，跟着的是 .env.local 里配的那份
 * 模型清单和密钥，不是个人口味 —— 换模型影响的是所有人的账单和出题质量。
 *
 * 故意不存地址和密钥：那两样只在 .env.local 里，前端改不了也读不到。
 */
DDL.push(`CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

/** 建表/播种时用的进程间互斥锁 key，避免多个实例同时初始化。 */
export const SCHEMA_LOCK_KEY = 728417231;

/** 所有表名，reset 脚本用。顺序无关，DROP 时统一带 CASCADE。 */
export const ALL_TABLES = [
  // app_settings 也列进来：db:reset 是回到「刚装好」的状态，
  // 留着一份指向已删模型的选择只会让人困惑
  'app_settings',
  'chat_messages',
  'conversations',
  'daily_stats',
  // dictionary 和 word_level 不列在这里：都是一次导入的只读词表，dictionary
  // 重建一次要花好几分钟，word_level 还得联外网抓 CSV。
  // db:reset 是“清掉学习数据重来”，不应该顺手把词表也删了。
  // 确实需要重建时用 npm run dict:import -- --force / npm run levels:import -- --force。
  'grammar_points',
  'materials',
  'mistakes',
  'review_logs',
  'sessions',
  'speech_attempts',
  'stage_content',
  'themes',
  'user_grammar',
  'user_words',
  'users',
  'words',
  // 写作环节已删，这张表不再创建；留在这里只为了在老库上能被清掉
  'writings',
] as const;
