/**
 * PostgreSQL 表结构。所有语句都是幂等的，进程启动时顺序执行一遍即可建库。
 * FSRS 相关字段（state/due/stability/difficulty/...）直接对应 ts-fsrs 的 Card 结构，
 * 单词和语法点各存一份，这样两者都能走同一套间隔重复调度。
 *
 * 两个约定：
 * - 时间列统一 `timestamp(0)`（不带时区，存 UTC 墙上时间）。连接建立时会 `SET TIME ZONE 'UTC'`，
 *   所以 SQL 里直接写 `now()` 就是 UTC，和 ts-fsrs 生成的 'YYYY-MM-DD HH:MM:SS' 可以直接比大小。
 * - 结构化字段统一 `jsonb`，读出来就是 JS 对象，写进去传 JSON 字符串。
 */

export const DDL: string[] = [];

DDL.push(`CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '学习者',
  level TEXT NOT NULL DEFAULT 'A1',
  goal TEXT NOT NULL DEFAULT 'daily_talk',
  interests JSONB NOT NULL DEFAULT '[]'::jsonb,
  daily_minutes INTEGER NOT NULL DEFAULT 30,
  new_words_per_day INTEGER NOT NULL DEFAULT 8,
  voice TEXT,
  ai_voice TEXT,
  speech_pace TEXT NOT NULL DEFAULT 'normal',
  onboarded INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

// 上面那句是 CREATE TABLE IF NOT EXISTS —— 对已存在的库它什么都不做。
// 新增列必须另写幂等 ALTER，否则老库升级后会在读这些列时直接报错。
//
// voice 和 ai_voice 是两回事，别弄混：
// - voice：浏览器 Web Speech 的语音包名字，给逐句朗读用，离线可用
// - ai_voice：StepFun realtime 的音色 id，给畅聊用，两边名字不通用
DDL.push(`ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_voice TEXT`);
DDL.push(
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS speech_pace TEXT NOT NULL DEFAULT 'normal'`,
);

DDL.push(`CREATE TABLE IF NOT EXISTS words (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term TEXT NOT NULL UNIQUE,
  phonetic TEXT,
  pos TEXT,
  meaning_zh TEXT NOT NULL,
  meaning_en TEXT,
  cefr TEXT NOT NULL DEFAULT 'A1',
  theme TEXT,
  example_en TEXT,
  example_zh TEXT,
  source TEXT NOT NULL DEFAULT 'seed',
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_theme ON words(theme)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_cefr ON words(cefr)`);
// findWordByTerm 走大小写不敏感匹配，这里给它一个可用的索引
DDL.push(`CREATE INDEX IF NOT EXISTS idx_words_term_lower ON words(lower(term))`);

// user_words：每个词的掌握状态。produced_count 记录"你主动说/写出来过几次"，
// 这是本站和普通背单词 app 的关键差别：只认得不算掌握。
DDL.push(`CREATE TABLE IF NOT EXISTS user_words (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  word_id INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
  state INTEGER NOT NULL DEFAULT 0,
  due TIMESTAMP(0) NOT NULL DEFAULT now(),
  stability DOUBLE PRECISION NOT NULL DEFAULT 0,
  difficulty DOUBLE PRECISION NOT NULL DEFAULT 0,
  elapsed_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  scheduled_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  learning_steps INTEGER NOT NULL DEFAULT 0,
  reps INTEGER NOT NULL DEFAULT 0,
  lapses INTEGER NOT NULL DEFAULT 0,
  last_review TIMESTAMP(0),
  produced_count INTEGER NOT NULL DEFAULT 0,
  seen_contexts JSONB NOT NULL DEFAULT '[]'::jsonb,
  starred INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(user_id, word_id)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_uw_due ON user_words(user_id, due)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_uw_state ON user_words(user_id, state)`);

DDL.push(`CREATE TABLE IF NOT EXISTS grammar_points (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title_zh TEXT NOT NULL,
  title_en TEXT NOT NULL,
  cefr TEXT NOT NULL DEFAULT 'A1',
  explain_zh TEXT NOT NULL,
  pattern TEXT,
  examples JSONB NOT NULL DEFAULT '[]'::jsonb,
  pitfalls JSONB NOT NULL DEFAULT '[]'::jsonb,
  ord INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT 'seed'
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS user_grammar (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  grammar_id INTEGER NOT NULL REFERENCES grammar_points(id) ON DELETE CASCADE,
  state INTEGER NOT NULL DEFAULT 0,
  due TIMESTAMP(0) NOT NULL DEFAULT now(),
  stability DOUBLE PRECISION NOT NULL DEFAULT 0,
  difficulty DOUBLE PRECISION NOT NULL DEFAULT 0,
  elapsed_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  scheduled_days DOUBLE PRECISION NOT NULL DEFAULT 0,
  learning_steps INTEGER NOT NULL DEFAULT 0,
  reps INTEGER NOT NULL DEFAULT 0,
  lapses INTEGER NOT NULL DEFAULT 0,
  last_review TIMESTAMP(0),
  error_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(user_id, grammar_id)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_ug_due ON user_grammar(user_id, due)`);

DDL.push(`CREATE TABLE IF NOT EXISTS review_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  kind TEXT NOT NULL,
  item_id INTEGER NOT NULL,
  rating INTEGER NOT NULL,
  mode TEXT NOT NULL DEFAULT 'recall',
  elapsed_ms INTEGER NOT NULL DEFAULT 0,
  reviewed_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_rl_user_time ON review_logs(user_id, reviewed_at)`);

DDL.push(`CREATE TABLE IF NOT EXISTS themes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  zh TEXT NOT NULL,
  en TEXT NOT NULL,
  tags TEXT NOT NULL DEFAULT '',
  last_used_on DATE
)`);

// 一天一条 session。stage_index 记录进行到第几环节，刷新页面能原地续上。
DDL.push(`CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  theme_slug TEXT NOT NULL,
  theme_zh TEXT NOT NULL,
  theme_en TEXT NOT NULL,
  target_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  review_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  grammar_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  stage_index INTEGER NOT NULL DEFAULT 0,
  stages_done JSONB NOT NULL DEFAULT '[]'::jsonb,
  minutes_spent DOUBLE PRECISION NOT NULL DEFAULT 0,
  completed_at TIMESTAMP(0),
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(user_id, day)
)`);

// AI 生成的环节内容缓存：同一天同一环节只生成一次，刷新不重复扣 token。
DDL.push(`CREATE TABLE IF NOT EXISTS stage_content (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  stage TEXT NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
  UNIQUE(session_id, stage)
)`);

// 错误档案：拼写/语法/发音/用词错误全部落这里，明天的例句和语法点会针对性复现。
DDL.push(`CREATE TABLE IF NOT EXISTS mistakes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  stage TEXT,
  word_id INTEGER,
  grammar_id INTEGER,
  wrong TEXT NOT NULL,
  correct TEXT,
  note_zh TEXT,
  resolved INTEGER NOT NULL DEFAULT 0,
  times INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_mistakes_user ON mistakes(user_id, resolved, created_at)`);

DDL.push(`CREATE TABLE IF NOT EXISTS conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id INTEGER,
  title TEXT NOT NULL DEFAULT '自由对话',
  theme_slug TEXT,
  target_word_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS chat_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  translation_zh TEXT,
  feedback JSONB,
  used_words JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_msg_conv ON chat_messages(conversation_id, id)`);

/*
 * writings 表连同写作环节一起去掉了，这里不再建。
 * 但它仍然留在 ALL_TABLES 里（标了注释），这样在老库上跑一次 db:reset
 * 就能把遗留的表清掉，不会长期挂着一张没人写的表。
 */

DDL.push(`CREATE TABLE IF NOT EXISTS speech_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id INTEGER,
  target TEXT NOT NULL,
  transcript TEXT NOT NULL,
  score INTEGER NOT NULL,
  detail JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

// 你自己扔进来的素材（文章/字幕/技术文档），AI 从里面抽词和语法点。
DDL.push(`CREATE TABLE IF NOT EXISTS materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'article',
  raw TEXT NOT NULL,
  summary_zh TEXT,
  word_count INTEGER NOT NULL DEFAULT 0,
  extracted INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) NOT NULL DEFAULT now()
)`);

DDL.push(`CREATE TABLE IF NOT EXISTS daily_stats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  reviews INTEGER NOT NULL DEFAULT 0,
  correct INTEGER NOT NULL DEFAULT 0,
  new_words INTEGER NOT NULL DEFAULT 0,
  produced INTEGER NOT NULL DEFAULT 0,
  spoken_seconds INTEGER NOT NULL DEFAULT 0,
  minutes DOUBLE PRECISION NOT NULL DEFAULT 0,
  UNIQUE(user_id, day)
)`);
DDL.push(`CREATE INDEX IF NOT EXISTS idx_ds_user_day ON daily_stats(user_id, day)`);

/**
 * dictionary：离线词典（ECDICT）。
 *
 * 为什么和 words 分开而不是合成一张表：
 * - words 是“你在学的词”，百到千量级，带主题、来源、例句，跟 user_words 关联；
 * - dictionary 是“查得到的词”，十万到百万量级，只用于查询。
 * 掘在一起的话，每次拉“今天要学的词”都要在百万行里扭，而且 source 字段
 * 会变成一个既要区分“学习来源”又要区分“是否词典条目”的缝合字段。
 *
 * translation 存 ECDICT 原始的多行中文释义（\n 分隔），definition 存英文释义。
 * frq 是词频排名（越小越常用）0 表示未知；tag 是考纲标签（zk/gk/cet4...）。
 */
DDL.push(`CREATE TABLE IF NOT EXISTS dictionary (
  word TEXT PRIMARY KEY,
  phonetic TEXT,
  definition TEXT,
  translation TEXT,
  pos TEXT,
  collins SMALLINT,
  oxford SMALLINT,
  tag TEXT,
  bnc INTEGER,
  frq INTEGER,
  exchange TEXT,
  detail TEXT,
  audio TEXT
)`);

// 查词走小写匹配（用户选中的词可能带大写或变形）
DDL.push(`CREATE INDEX IF NOT EXISTS idx_dict_word_lower ON dictionary(lower(word))`);
// 按词频挑“值得学的词”时用
DDL.push(`CREATE INDEX IF NOT EXISTS idx_dict_frq ON dictionary(frq) WHERE frq > 0`);

/** 建表/播种时用的进程间互斥锁 key，避免多个实例同时初始化。 */
export const SCHEMA_LOCK_KEY = 728417231;

/** 所有表名，reset 脚本用。顺序无关，DROP 时统一带 CASCADE。 */
export const ALL_TABLES = [
  'chat_messages',
  'conversations',
  'daily_stats',
  // dictionary 不列在这里：它是一次导入的只读词典，重建一次要花好几分钟。
  // db:reset 是“清掉学习数据重来”，不应该顺手把词典也删了。
  // 确实需要重建词典时用 npm run dict:import -- --force。
  'grammar_points',
  'materials',
  'mistakes',
  'review_logs',
  'sessions',
  'speech_attempts',
  'stage_content',
  'themes',
  'user_grammar',
  'user_words',
  'users',
  'words',
  // 写作环节已删，这张表不再创建；留在这里只为了在老库上能被清掉
  'writings',
] as const;
